import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Loader2, Play, X } from "lucide-react";

import { useI18n } from "@/lib/i18n";
import {
  listUserLiveGreetings,
  type AdminLiveGreetingRow,
} from "@/lib/admin/user-live-cards.functions";

/** Administration review of every live greeting card generated by users. */
export function UserLiveCardsPage() {
  const { t, lang } = useI18n();
  const fetchRows = useServerFn(listUserLiveGreetings);
  const [open, setOpen] = useState<AdminLiveGreetingRow | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["admin-user-live-cards"],
    queryFn: () => fetchRows({ data: undefined }),
  });

  const rows = data ?? [];
  const fmt = (v: string | null) => (v ? new Date(v).toLocaleString(lang) : "—");

  return (
    <div>
      <h1 className="font-[Fraunces] text-2xl font-semibold text-foreground">{t("ulc_title")}</h1>
      <p className="mt-1 text-sm text-muted-foreground">{t("ulc_sub")}</p>

      {isLoading ? (
        <div className="mt-6 flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" /> {t("ulc_loading")}
        </div>
      ) : rows.length === 0 ? (
        <div className="mt-6 rounded-2xl border border-border/60 bg-card/70 p-8 text-center text-sm text-muted-foreground">
          {t("ulc_empty")}
        </div>
      ) : (
        <div className="mt-6 overflow-x-auto rounded-2xl border border-border/60 bg-card/70">
          <table className="w-full min-w-[900px] text-left text-xs">
            <thead className="border-b border-border/60 text-muted-foreground">
              <tr>
                <th className="p-3">#</th>
                <th className="p-3">{t("ulc_user")}</th>
                <th className="p-3">{t("ulc_motion")}</th>
                <th className="p-3">{t("ulc_duration")}</th>
                <th className="p-3">{t("ulc_status")}</th>
                <th className="p-3">{t("ulc_created")}</th>
                <th className="p-3" />
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id} className="border-b border-border/40 last:border-0">
                  <td className="p-3">
                    <button
                      type="button"
                      onClick={() => setOpen(row)}
                      className="block h-14 w-14 overflow-hidden rounded-md border border-border/60 bg-muted"
                    >
                      {row.image_url ? (
                        <img src={row.image_url} alt={row.motion_prompt} className="h-full w-full object-cover" />
                      ) : null}
                    </button>
                  </td>
                  <td className="p-3 text-muted-foreground">{row.user_email ?? row.user_id}</td>
                  <td className="max-w-[280px] truncate p-3 text-muted-foreground">{row.motion_prompt || "—"}</td>
                  <td className="p-3 text-muted-foreground">{row.duration_seconds}s</td>
                  <td className="p-3 text-muted-foreground">
                    {row.status}
                    {row.deleted_at ? ` · ${t("ulc_deleted_flag")}` : ""}
                  </td>
                  <td className="p-3 text-muted-foreground">{fmt(row.created_at)}</td>
                  <td className="p-3 text-right">
                    <button
                      type="button"
                      onClick={() => setOpen(row)}
                      className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-1.5 font-medium text-primary-foreground"
                    >
                      <Play className="h-3.5 w-3.5" /> {t("ulc_open")}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-5 backdrop-blur-sm">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-border/60 bg-card p-5 shadow-xl">
            <div className="mb-4 flex items-start justify-between gap-4">
              <h3 className="font-[Fraunces] text-lg font-semibold text-foreground">{t("ulc_title")}</h3>
              <button
                type="button"
                onClick={() => setOpen(null)}
                aria-label={t("llc_close")}
                className="flex h-8 w-8 items-center justify-center rounded-full border border-border/60 hover:bg-secondary"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {open.video_url ? (
              <video src={open.video_url} controls playsInline className="mb-4 max-h-[55vh] w-full rounded-xl bg-black" />
            ) : open.image_url ? (
              <img src={open.image_url} alt={open.motion_prompt} className="mb-4 w-full rounded-xl object-contain" />
            ) : null}

            <dl className="grid gap-3 text-xs text-muted-foreground sm:grid-cols-2">
              <Field label={t("ulc_user")} value={open.user_email ?? open.user_id} />
              <Field label={t("ulc_status")} value={open.status} />
              <Field label={t("ulc_image_prompt")} value={open.image_prompt || "—"} />
              <Field label={t("ulc_motion")} value={open.motion_prompt || "—"} />
              <Field label={t("ulc_motion_en")} value={open.motion_prompt_en || "—"} />
              <Field label={t("ulc_duration")} value={`${open.duration_seconds}s`} />
              <Field label={t("ulc_format")} value={open.aspect_ratio ?? "—"} />
              <Field label={t("ulc_generator")} value={open.generator_key ?? "—"} />
              <Field label={t("ulc_created")} value={fmt(open.created_at)} />
            </dl>
          </div>
        </div>
      )}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="font-medium text-foreground">{label}</dt>
      <dd className="break-words">{value}</dd>
    </div>
  );
}
