import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Loader2, Play, RotateCcw, Send, Trash2, Undo2, X } from "lucide-react";
import { toast } from "sonner";

import { useI18n } from "@/lib/i18n";
import {
  adminDeleteLiveGreeting,
  adminDeliverLiveGreeting,
  adminPurgeLiveGreeting,
  adminRestoreLiveGreeting,
  adminReturnLiveGreetingToUser,
  listUserLiveGreetings,
  type AdminLiveGreetingRow,
} from "@/lib/admin/user-live-cards.functions";

/** Administration review of every live greeting card generated by users. */
export function UserLiveCardsPage() {
  const { t, lang } = useI18n();
  const fetchRows = useServerFn(listUserLiveGreetings);
  const removeRow = useServerFn(adminDeleteLiveGreeting);
  const restoreRow = useServerFn(adminRestoreLiveGreeting);
  const purgeRow = useServerFn(adminPurgeLiveGreeting);
  const deliverRow = useServerFn(adminDeliverLiveGreeting);
  const returnRow = useServerFn(adminReturnLiveGreetingToUser);
  const queryClient = useQueryClient();
  const [open, setOpen] = useState<AdminLiveGreetingRow | null>(null);
  const [confirmPurge, setConfirmPurge] = useState<AdminLiveGreetingRow | null>(null);
  const [deliverTo, setDeliverTo] = useState<AdminLiveGreetingRow | null>(null);
  const [email, setEmail] = useState("");

  const { data, isLoading } = useQuery({
    queryKey: ["admin-user-live-cards"],
    queryFn: () => fetchRows({ data: undefined }),
  });

  const rows = data ?? [];
  const fmt = (v: string | null) => (v ? new Date(v).toLocaleString(lang) : "—");

  const done = (message: string) => {
    toast.success(message);
    setOpen(null);
    setConfirmPurge(null);
    setDeliverTo(null);
    setEmail("");
    queryClient.invalidateQueries({ queryKey: ["admin-user-live-cards"] });
  };
  const fail = (e: unknown) => {
    const code = e instanceof Error ? e.message : "error";
    if (code === "retention_active") toast.error(t("ulc_retention_active"));
    else if (code === "user_not_found") toast.error(t("ulc_user_not_found"));
    else if (code === "generation_incomplete") toast.error(t("ulc_not_generated"));
    else toast.error(code);
  };

  const del = useMutation({
    mutationFn: (id: string) => removeRow({ data: { animationId: id } }),
    onSuccess: () => done(t("ulc_deleted_toast")),
    onError: fail,
  });
  const restore = useMutation({
    mutationFn: (id: string) => restoreRow({ data: { animationId: id } }),
    onSuccess: () => done(t("ulc_restored_toast")),
    onError: fail,
  });
  const purge = useMutation({
    mutationFn: (id: string) => purgeRow({ data: { animationId: id } }),
    onSuccess: () => done(t("ulc_purged_toast")),
    onError: fail,
  });
  const deliver = useMutation({
    mutationFn: (vars: { id: string; email: string }) =>
      deliverRow({ data: { animationId: vars.id, email: vars.email } }),
    onSuccess: () => done(t("ulc_delivered_toast")),
    onError: fail,
  });

  const returnToUser = useMutation({
    mutationFn: (id: string) => returnRow({ data: { animationId: id } }),
    onSuccess: () => done(t("ulc_returned_toast")),
    onError: fail,
  });

  return (
    <div>
      <h1 className="font-[Fraunces] text-2xl font-semibold text-foreground">{t("ulc_title")}</h1>
      <p className="mt-1 text-sm text-muted-foreground">{t("ulc_sub")}</p>

      {isLoading ? (
        <div className="mt-6 flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" /> {t("ulc_loading")}
        </div>
      ) : rows.length === 0 ? (
        <div className="mt-6 rounded-2xl border border-border/60 bg-card/70 p-8 text-center text-sm text-muted-foreground">
          {t("ulc_empty")}
        </div>
      ) : (
        <div className="mt-6 overflow-x-auto rounded-2xl border border-border/60 bg-card/70">
          <table className="w-full min-w-[900px] text-left text-xs">
            <thead className="border-b border-border/60 text-muted-foreground">
              <tr>
                <th className="p-3">#</th>
                <th className="p-3">{t("ulc_user")}</th>
                <th className="p-3">{t("ulc_motion")}</th>
                <th className="p-3">{t("ulc_duration")}</th>
                <th className="p-3">{t("ulc_status")}</th>
                <th className="p-3">{t("ulc_delivery")}</th>
                <th className="p-3">{t("ulc_created")}</th>
                <th className="p-3" />
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id} className="border-b border-border/40 last:border-0">
                  <td className="p-3">
                    <button
                      type="button"
                      onClick={() => setOpen(row)}
                      className="block h-14 w-14 overflow-hidden rounded-md border border-border/60 bg-muted"
                    >
                      {row.image_url ? (
                        <img src={row.image_url} alt={row.motion_prompt} className="h-full w-full object-cover" />
                      ) : null}
                    </button>
                  </td>
                  <td className="p-3 text-muted-foreground">{row.user_email ?? row.user_id}</td>
                  <td className="max-w-[280px] truncate p-3 text-muted-foreground">{row.motion_prompt || "—"}</td>
                  <td className="p-3 text-muted-foreground">{row.duration_seconds}s</td>
                  <td className="p-3 text-muted-foreground">
                    {row.status}
                    {row.deleted_at ? ` · ${t("ulc_deleted_flag")}` : ""}
                  </td>
                  <td className="p-3">
                    <span
                      className={
                        row.delivered ? "font-medium text-primary" : "font-medium text-destructive"
                      }
                    >
                      {row.delivered ? t("ulc_delivered") : t("ulc_not_delivered")}
                    </span>
                  </td>
                  <td className="p-3 text-muted-foreground">{fmt(row.created_at)}</td>
                  <td className="p-3 text-right">
                    <div className="flex justify-end gap-2">
                      {row.status === "ready" && (
                        <button
                          type="button"
                          onClick={() => {
                            setDeliverTo(row);
                            setEmail(row.user_email ?? "");
                          }}
                          className="inline-flex items-center gap-1.5 rounded-full border border-primary/50 px-3 py-1.5 font-medium text-primary hover:bg-primary/10"
                        >
                          <Send className="h-3.5 w-3.5" />
                          {row.delivered ? t("ulc_retry_delivery") : t("ulc_send_to_user")}
                        </button>
                      )}
                      {row.status === "ready" && (
                        <button
                          type="button"
                          disabled={returnToUser.isPending}
                          onClick={() => returnToUser.mutate(row.id)}
                          className="inline-flex items-center gap-1.5 rounded-full border border-border/60 px-3 py-1.5 font-medium hover:border-primary/50 disabled:opacity-60"
                        >
                          <Undo2 className="h-3.5 w-3.5" />
                          {t("ulc_return_to_user")}
                        </button>
                      )}
                      <button
                        type="button"
                        onClick={() => setOpen(row)}
                        className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-1.5 font-medium text-primary-foreground"
                      >
                        <Play className="h-3.5 w-3.5" /> {t("ulc_open")}
                      </button>
                      {row.deleted_at ? (
                        <>
                          <button
                            type="button"
                            onClick={() => restore.mutate(row.id)}
                            className="inline-flex items-center gap-1.5 rounded-full border border-border/60 px-3 py-1.5 font-medium hover:border-primary/50"
                          >
                            <RotateCcw className="h-3.5 w-3.5" /> {t("ulc_restore")}
                          </button>
                          <button
                            type="button"
                            onClick={() => setConfirmPurge(row)}
                            className="inline-flex items-center gap-1.5 rounded-full border border-destructive/40 px-3 py-1.5 font-medium text-destructive hover:bg-destructive/10"
                          >
                            <Trash2 className="h-3.5 w-3.5" /> {t("ulc_purge")}
                          </button>
                        </>
                      ) : (
                        <button
                          type="button"
                          onClick={() => del.mutate(row.id)}
                          className="inline-flex items-center gap-1.5 rounded-full border border-destructive/40 px-3 py-1.5 font-medium text-destructive hover:bg-destructive/10"
                        >
                          <Trash2 className="h-3.5 w-3.5" /> {t("ulc_delete")}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-5 backdrop-blur-sm">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-border/60 bg-card p-5 shadow-xl">
            <div className="mb-4 flex items-start justify-between gap-4">
              <h3 className="font-[Fraunces] text-lg font-semibold text-foreground">{t("ulc_title")}</h3>
              <button
                type="button"
                onClick={() => setOpen(null)}
                aria-label={t("llc_close")}
                className="flex h-8 w-8 items-center justify-center rounded-full border border-border/60 hover:bg-secondary"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {open.video_url ? (
              <video src={open.video_url} controls playsInline className="mb-4 max-h-[55vh] w-full rounded-xl bg-black" />
            ) : open.image_url ? (
              <img src={open.image_url} alt={open.motion_prompt} className="mb-4 w-full rounded-xl object-contain" />
            ) : null}

            <dl className="grid gap-3 text-xs text-muted-foreground sm:grid-cols-2">
              <Field label={t("ulc_user")} value={open.user_email ?? open.user_id} />
              <Field label={t("ulc_status")} value={open.status} />
              <Field label={t("ulc_image_prompt")} value={open.image_prompt || "—"} />
              <Field label={t("ulc_motion")} value={open.motion_prompt || "—"} />
              <Field label={t("ulc_motion_en")} value={open.motion_prompt_en || "—"} />
              <Field label={t("ulc_greeting")} value={open.greeting_text || "—"} />
              <Field label={t("ulc_duration")} value={`${open.duration_seconds}s`} />
              <Field label={t("ulc_format")} value={open.aspect_ratio ?? "—"} />
              <Field label={t("ulc_generator")} value={open.generator_key ?? "—"} />
              <Field label={t("ulc_created")} value={fmt(open.created_at)} />
              <Field label={t("ulc_deleted_at")} value={fmt(open.deleted_at)} />
              <Field label={t("ulc_purge_after")} value={fmt(open.purge_after)} />
            </dl>
          </div>
        </div>
      )}

      {deliverTo && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-background/80 p-5 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-2xl border border-border/60 bg-card p-6 shadow-xl">
            <h3 className="font-[Fraunces] text-lg font-semibold text-foreground">
              {deliverTo.delivered ? t("ulc_retry_delivery") : t("ulc_send_to_user")}
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">{t("ulc_deliver_desc")}</p>
            <label className="mt-4 block text-xs font-medium text-foreground" htmlFor="ulc-email">
              {t("ulc_deliver_email")}
            </label>
            <input
              id="ulc-email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={deliverTo.user_email ?? ""}
              className="mt-1 w-full rounded-xl border border-border/60 bg-background/70 px-4 py-2.5 text-sm outline-none focus:border-primary/60"
            />
            <div className="mt-6 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setDeliverTo(null)}
                className="rounded-full border border-border/60 px-5 py-2.5 text-sm hover:bg-secondary"
              >
                {t("ulc_cancel")}
              </button>
              <button
                type="button"
                disabled={deliver.isPending}
                onClick={() =>
                  deliver.mutate({
                    id: deliverTo.id,
                    email: email.trim() === (deliverTo.user_email ?? "") ? "" : email.trim(),
                  })
                }
                className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-60"
              >
                {deliver.isPending ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
                {t("ulc_deliver_confirm")}
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmPurge && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-background/80 p-5 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-2xl border border-border/60 bg-card p-6 shadow-xl">
            <h3 className="font-[Fraunces] text-lg font-semibold text-foreground">
              {t("ulc_purge_confirm_title")}
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">{t("ulc_purge_confirm_desc")}</p>
            <div className="mt-6 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setConfirmPurge(null)}
                className="rounded-full border border-border/60 px-5 py-2.5 text-sm hover:bg-secondary"
              >
                {t("ulc_cancel")}
              </button>
              <button
                type="button"
                disabled={purge.isPending}
                onClick={() => purge.mutate(confirmPurge.id)}
                className="rounded-full bg-destructive px-5 py-2.5 text-sm font-medium text-destructive-foreground disabled:opacity-60"
              >
                {t("ulc_purge")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="font-medium text-foreground">{label}</dt>
      <dd className="break-words">{value}</dd>
    </div>
  );
}
