/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PersonalOrdersRouteImport } from './routes/personal-orders'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CorporateOrdersRouteImport } from './routes/corporate-orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalOrdersRoute = PersonalOrdersRouteImport.update({
  id: '/personal-orders',
  path: '/personal-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateOrdersRoute = CorporateOrdersRouteImport.update({
  id: '/corporate-orders',
  path: '/corporate-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/corporate-orders': typeof CorporateOrdersRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/personal-orders': typeof PersonalOrdersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/corporate-orders': typeof CorporateOrdersRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/personal-orders': typeof PersonalOrdersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/corporate-orders': typeof CorporateOrdersRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/personal-orders': typeof PersonalOrdersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/catalog'
    | '/contact'
    | '/corporate-orders'
    | '/create'
    | '/daily'
    | '/personal-orders'
    | '/pricing'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/catalog'
    | '/contact'
    | '/corporate-orders'
    | '/create'
    | '/daily'
    | '/personal-orders'
    | '/pricing'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/catalog'
    | '/contact'
    | '/corporate-orders'
    | '/create'
    | '/daily'
    | '/personal-orders'
    | '/pricing'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  CorporateOrdersRoute: typeof CorporateOrdersRoute
  CreateRoute: typeof CreateRoute
  DailyRoute: typeof DailyRoute
  PersonalOrdersRoute: typeof PersonalOrdersRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-orders': {
      id: '/personal-orders'
      path: '/personal-orders'
      fullPath: '/personal-orders'
      preLoaderRoute: typeof PersonalOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-orders': {
      id: '/corporate-orders'
      path: '/corporate-orders'
      fullPath: '/corporate-orders'
      preLoaderRoute: typeof CorporateOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  CorporateOrdersRoute: CorporateOrdersRoute,
  CreateRoute: CreateRoute,
  DailyRoute: DailyRoute,
  PersonalOrdersRoute: PersonalOrdersRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
