import type { Background, CardVariant } from "./types";
import { defaultTextDesign } from "./types";

const NOW = "2026-07-01T09:00:00.000Z";

export const MOCK_BACKGROUNDS: Background[] = [
  {
    id: "BG-001",
    internalName: "roses-soft-morning",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "vertical",
    aspectRatio: "4:5",
    visualStyles: ["romantic", "floral", "gentle"],
    visualObjects: ["roses", "flowers"],
    mood: ["warm", "peaceful"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 0,
  },
  {
    id: "BG-002",
    internalName: "candles-warm-glow",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "square",
    aspectRatio: "1:1",
    visualStyles: ["elegant", "classic"],
    visualObjects: ["candles", "hearts"],
    mood: ["warm", "emotional"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 1,
  },
  {
    id: "BG-003",
    internalName: "mountain-sky-serene",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "horizontal",
    aspectRatio: "16:9",
    visualStyles: ["nature", "minimalist", "modern"],
    visualObjects: ["landscape", "sky"],
    mood: ["peaceful", "inspirational"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 5,
  },
  {
    id: "BG-004",
    internalName: "birthday-balloons-party",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "vertical",
    aspectRatio: "4:5",
    visualStyles: ["funny", "modern", "children"],
    visualObjects: ["balloons", "cake", "stars"],
    mood: ["joyful", "playful"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 2,
  },
  {
    id: "BG-005",
    internalName: "church-blessing-light",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "vertical",
    aspectRatio: "4:5",
    visualStyles: ["christian", "classic", "elegant"],
    visualObjects: ["church", "cross"],
    mood: ["solemn", "peaceful"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 7,
  },
  {
    id: "BG-006",
    internalName: "gift-box-elegant",
    sourceImageUrl: "",
    thumbnailUrl: "",
    orientation: "square",
    aspectRatio: "1:1",
    visualStyles: ["elegant", "luxurious", "minimalist"],
    visualObjects: ["gift_box"],
    mood: ["warm", "solemn"],
    status: "draft",
    createdAt: NOW,
    updatedAt: NOW,
    gradientIndex: 3,
  },
];

function td() { return defaultTextDesign(); }

export const MOCK_VARIANTS: CardVariant[] = [
  // Background BG-001 (roses) reused across three variants
  {
    id: "CV-001",
    backgroundId: "BG-001",
    internalName: "roses-birthday-mom",
    primaryOccasion: "birthday",
    additionalOccasions: [],
    recipients: ["mom"],
    styles: ["romantic", "gentle", "floral"],
    visualObjects: ["roses"],
    mood: ["warm"],
    ageGroup: "adults",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Happy Birthday, Mom", shortDescription: "A tender bouquet for the one who gave you everything.", textOnCard: "Happy Birthday, Mom!", searchKeywords: ["mom", "birthday", "roses"] },
      ru: { locale: "ru", catalogTitle: "С Днём Рождения, мама", shortDescription: "Нежный букет для самого дорогого человека.", textOnCard: "С Днём Рождения, мама!", searchKeywords: ["мама", "день рождения"] },
      uk: { locale: "uk", catalogTitle: "З Днем Народження, мамо", shortDescription: "Ніжний букет для найріднішої людини.", textOnCard: "З Днем Народження, мамо!", searchKeywords: ["мама", "день народження"] },
      de: { locale: "de", catalogTitle: "Alles Gute zum Geburtstag, Mama", shortDescription: "Ein zarter Strauß für den wichtigsten Menschen.", textOnCard: "Alles Gute zum Geburtstag, Mama!", searchKeywords: ["mama", "geburtstag"] },
      fr: { locale: "fr", catalogTitle: "Joyeux anniversaire, maman", shortDescription: "Un bouquet tendre pour la personne la plus précieuse.", textOnCard: "Joyeux anniversaire, maman !", searchKeywords: ["maman", "anniversaire"] },
      pl: { locale: "pl", catalogTitle: "Wszystkiego najlepszego, Mamo", shortDescription: "Delikatny bukiet dla najważniejszej osoby.", textOnCard: "Wszystkiego najlepszego, Mamo!", searchKeywords: ["mama", "urodziny"] },
    },
    textDesign: td(),
    displayOrder: 1,
    isNew: true,
    isPopular: true,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-002",
    backgroundId: "BG-001",
    internalName: "roses-thank-you",
    primaryOccasion: "thank_you",
    additionalOccasions: [],
    recipients: ["universal", "female_friend"],
    styles: ["gentle", "floral"],
    visualObjects: ["roses"],
    mood: ["warm"],
    ageGroup: "all_ages",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Thank You", shortDescription: "A quiet, heartfelt thank-you.", textOnCard: "Thank you, from the heart.", searchKeywords: ["thanks"] },
      ru: { locale: "ru", catalogTitle: "Спасибо", shortDescription: "Тихая, искренняя благодарность.", textOnCard: "Спасибо от всего сердца.", searchKeywords: ["спасибо"] },
      de: { locale: "de", catalogTitle: "Danke", shortDescription: "Ein leises, aufrichtiges Dankeschön.", textOnCard: "Danke, von Herzen.", searchKeywords: ["danke"] },
    },
    textDesign: td(),
    displayOrder: 2,
    isNew: false,
    isPopular: false,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-003",
    backgroundId: "BG-001",
    internalName: "roses-nice-day",
    primaryOccasion: "nice_day",
    additionalOccasions: ["good_morning"],
    recipients: ["universal"],
    styles: ["gentle", "floral"],
    visualObjects: ["roses"],
    mood: ["warm", "joyful"],
    ageGroup: "all_ages",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Have a Beautiful Day", shortDescription: "A gentle morning wish.", textOnCard: "Have a beautiful day.", searchKeywords: [] },
      ru: { locale: "ru", catalogTitle: "Прекрасного дня", shortDescription: "Нежное пожелание доброго дня.", textOnCard: "Прекрасного дня!", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 3,
    isNew: true,
    isPopular: false,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: true,
    status: "draft",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-004",
    backgroundId: "BG-002",
    internalName: "candles-anniversary",
    primaryOccasion: "anniversary",
    additionalOccasions: [],
    recipients: ["wife", "husband"],
    styles: ["romantic", "elegant"],
    visualObjects: ["candles", "hearts"],
    mood: ["emotional", "warm"],
    ageGroup: "adults",
    orientation: "square",
    translations: {
      en: { locale: "en", catalogTitle: "Our Anniversary", shortDescription: "Warm candlelight for a warm year together.", textOnCard: "Happy Anniversary, my love.", searchKeywords: [] },
      ru: { locale: "ru", catalogTitle: "Наша годовщина", shortDescription: "Тёплый свет свечей — как наши годы вместе.", textOnCard: "С годовщиной, любовь моя.", searchKeywords: [] },
      fr: { locale: "fr", catalogTitle: "Notre anniversaire", shortDescription: "La chaleur des bougies pour une année pleine d'amour.", textOnCard: "Joyeux anniversaire, mon amour.", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 4,
    isNew: false,
    isPopular: true,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-005",
    backgroundId: "BG-002",
    internalName: "candles-condolences",
    primaryOccasion: "condolences",
    additionalOccasions: [],
    recipients: ["universal"],
    styles: ["classic", "elegant"],
    visualObjects: ["candles"],
    mood: ["solemn", "peaceful"],
    ageGroup: "adults",
    orientation: "square",
    translations: {
      en: { locale: "en", catalogTitle: "With Deepest Sympathy", shortDescription: "A quiet flame in a time of grief.", textOnCard: "With deepest sympathy.", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 5,
    isNew: false,
    isPopular: false,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: false,
    status: "hidden",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-006",
    backgroundId: "BG-003",
    internalName: "landscape-encouragement",
    primaryOccasion: "encouragement",
    additionalOccasions: ["thinking_of_you"],
    recipients: ["friend", "colleague"],
    styles: ["nature", "modern", "minimalist"],
    visualObjects: ["landscape", "sky"],
    mood: ["inspirational", "peaceful"],
    ageGroup: "all_ages",
    orientation: "horizontal",
    translations: {
      en: { locale: "en", catalogTitle: "You've Got This", shortDescription: "Big skies for big days.", textOnCard: "You've got this.", searchKeywords: [] },
      pl: { locale: "pl", catalogTitle: "Dasz radę", shortDescription: "Wielkie niebo na wielkie dni.", textOnCard: "Dasz radę.", searchKeywords: [] },
    },
    textDesign: { ...td(), y: 20, alignment: "left", x: 8, width: 60 },
    displayOrder: 6,
    isNew: true,
    isPopular: false,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-007",
    backgroundId: "BG-003",
    internalName: "landscape-safe-travels",
    primaryOccasion: "safe_travels",
    additionalOccasions: [],
    recipients: ["universal"],
    styles: ["nature", "minimalist"],
    visualObjects: ["landscape"],
    mood: ["peaceful"],
    ageGroup: "all_ages",
    orientation: "horizontal",
    translations: {
      en: { locale: "en", catalogTitle: "Safe Travels", shortDescription: "A wide horizon for a wide adventure.", textOnCard: "Safe travels, friend.", searchKeywords: [] },
    },
    textDesign: { ...td(), y: 20 },
    displayOrder: 7,
    isNew: false,
    isPopular: false,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: true,
    status: "draft",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-008",
    backgroundId: "BG-004",
    internalName: "balloons-birthday-friend",
    primaryOccasion: "birthday",
    additionalOccasions: [],
    recipients: ["friend", "female_friend"],
    styles: ["funny", "modern"],
    visualObjects: ["balloons", "cake"],
    mood: ["joyful", "playful"],
    ageGroup: "all_ages",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Big Day, Bigger Smile", shortDescription: "Confetti energy for your favorite person.", textOnCard: "Happy Birthday!", searchKeywords: [] },
      ru: { locale: "ru", catalogTitle: "Большой день, большая улыбка", shortDescription: "Праздничная энергия для любимого человека.", textOnCard: "С Днём Рождения!", searchKeywords: [] },
      uk: { locale: "uk", catalogTitle: "Великий день, велика усмішка", shortDescription: "Святковий настрій для найкращих.", textOnCard: "З Днем Народження!", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 8,
    isNew: true,
    isPopular: true,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-009",
    backgroundId: "BG-004",
    internalName: "balloons-birthday-kid",
    primaryOccasion: "birthday",
    additionalOccasions: [],
    recipients: ["son", "daughter", "grandson", "granddaughter"],
    styles: ["children", "funny"],
    visualObjects: ["balloons", "cake", "stars"],
    mood: ["joyful", "playful"],
    ageGroup: "kids",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Happy Birthday!", shortDescription: "A colorful cheer for a little celebration.", textOnCard: "Happy Birthday!", searchKeywords: [] },
      de: { locale: "de", catalogTitle: "Alles Gute zum Geburtstag!", shortDescription: "Bunter Jubel für die kleine Feier.", textOnCard: "Alles Gute zum Geburtstag!", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 9,
    isNew: false,
    isPopular: true,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-010",
    backgroundId: "BG-005",
    internalName: "church-blessing-family",
    primaryOccasion: "christian_blessing",
    additionalOccasions: ["prayer_support"],
    recipients: ["whole_family", "universal"],
    styles: ["christian", "classic"],
    visualObjects: ["church", "cross"],
    mood: ["solemn", "peaceful"],
    ageGroup: "all_ages",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Blessings on Your Family", shortDescription: "A quiet blessing for the ones you love.", textOnCard: "May blessings surround your home.", searchKeywords: [] },
      ru: { locale: "ru", catalogTitle: "Благословений вашей семье", shortDescription: "Тихое благословение для близких.", textOnCard: "Пусть благословение окружает ваш дом.", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 10,
    isNew: false,
    isPopular: false,
    isRecommended: true,
    allowSharing: true,
    allowDownloading: true,
    status: "published",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-011",
    backgroundId: "BG-005",
    internalName: "church-easter",
    primaryOccasion: "easter",
    additionalOccasions: [],
    recipients: ["universal", "whole_family"],
    styles: ["christian", "elegant"],
    visualObjects: ["church", "cross"],
    mood: ["solemn", "joyful"],
    ageGroup: "all_ages",
    orientation: "vertical",
    translations: {
      en: { locale: "en", catalogTitle: "Blessed Easter", shortDescription: "A luminous Easter greeting.", textOnCard: "Blessed Easter.", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 11,
    isNew: false,
    isPopular: false,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: true,
    status: "archived",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "CV-012",
    backgroundId: "BG-006",
    internalName: "gift-thank-you-boss",
    primaryOccasion: "thank_you",
    additionalOccasions: [],
    recipients: ["colleague", "boss"],
    styles: ["elegant", "minimalist", "luxurious"],
    visualObjects: ["gift_box"],
    mood: ["warm", "solemn"],
    ageGroup: "adults",
    orientation: "square",
    translations: {
      en: { locale: "en", catalogTitle: "With Appreciation", shortDescription: "A refined thank-you for the workplace.", textOnCard: "With appreciation.", searchKeywords: [] },
    },
    textDesign: td(),
    displayOrder: 12,
    isNew: true,
    isPopular: false,
    isRecommended: false,
    allowSharing: true,
    allowDownloading: true,
    status: "draft",
    createdAt: NOW,
    updatedAt: NOW,
  },
];