import type { Taxonomy, TaxonomyItem } from "./types";

function it(
  key: string,
  names: { en: string; ru?: string; uk?: string; de?: string; fr?: string; pl?: string },
  order: number,
  icon?: string,
  parentKey?: string,
): TaxonomyItem {
  return {
    key,
    names,
    icon,
    displayOrder: order,
    active: true,
    parentKey,
  };
}

// Sanitized labels — no personal names anywhere.
export const DEFAULT_TAXONOMY: Taxonomy = {
  occasion: [
    it("birthday", { en: "Birthday", ru: "День рождения", uk: "День народження", de: "Geburtstag", fr: "Anniversaire", pl: "Urodziny" }, 1, "🎂"),
    it("anniversary", { en: "Anniversary", ru: "Годовщина", uk: "Річниця", de: "Jahrestag", fr: "Anniversaire de mariage", pl: "Rocznica" }, 2, "💍"),
    it("wedding", { en: "Wedding", ru: "Свадьба", uk: "Весілля", de: "Hochzeit", fr: "Mariage", pl: "Ślub" }, 3, "💒"),
    it("engagement", { en: "Engagement", ru: "Помолвка", uk: "Заручини", de: "Verlobung", fr: "Fiançailles", pl: "Zaręczyny" }, 4, "💐"),
    it("new_baby", { en: "New Baby", ru: "Рождение малыша", uk: "Народження дитини", de: "Baby", fr: "Naissance", pl: "Narodziny" }, 5, "👶"),
    it("baptism", { en: "Baptism", ru: "Крестины", uk: "Хрестини", de: "Taufe", fr: "Baptême", pl: "Chrzest" }, 6, "🕊️"),
    it("graduation", { en: "Graduation", ru: "Выпускной", uk: "Випускний", de: "Abschluss", fr: "Diplôme", pl: "Ukończenie szkoły" }, 7, "🎓"),
    it("housewarming", { en: "Housewarming", ru: "Новоселье", uk: "Новосілля", de: "Einzug", fr: "Crémaillère", pl: "Parapetówka" }, 8, "🏠"),
    it("retirement", { en: "Retirement", ru: "Выход на пенсию", uk: "Вихід на пенсію", de: "Ruhestand", fr: "Retraite", pl: "Emerytura" }, 9, "🎖️"),
    it("new_year", { en: "New Year", ru: "Новый год", uk: "Новий рік", de: "Neujahr", fr: "Nouvel An", pl: "Nowy Rok" }, 10, "🎆"),
    it("christmas", { en: "Christmas", ru: "Рождество", uk: "Різдво", de: "Weihnachten", fr: "Noël", pl: "Boże Narodzenie" }, 11, "🎄"),
    it("easter", { en: "Easter", ru: "Пасха", uk: "Великдень", de: "Ostern", fr: "Pâques", pl: "Wielkanoc" }, 12, "🐣"),
    it("valentines", { en: "Valentine's Day", ru: "День святого Валентина", uk: "День Валентина", de: "Valentinstag", fr: "Saint-Valentin", pl: "Walentynki" }, 13, "💝"),
    it("mothers_day", { en: "Mother's Day", ru: "День матери", uk: "День матері", de: "Muttertag", fr: "Fête des mères", pl: "Dzień Matki" }, 14, "🌷"),
    it("fathers_day", { en: "Father's Day", ru: "День отца", uk: "День батька", de: "Vatertag", fr: "Fête des pères", pl: "Dzień Ojca" }, 15, "🧔"),
    it("good_morning", { en: "Good Morning", ru: "Доброе утро", uk: "Доброго ранку", de: "Guten Morgen", fr: "Bonjour", pl: "Dzień dobry" }, 16, "☀️"),
    it("nice_day", { en: "Have a Nice Day", ru: "Приятного дня", uk: "Гарного дня", de: "Schönen Tag", fr: "Bonne journée", pl: "Miłego dnia" }, 17, "🌼"),
    it("good_evening", { en: "Good Evening", ru: "Добрый вечер", uk: "Добрий вечір", de: "Guten Abend", fr: "Bonsoir", pl: "Dobry wieczór" }, 18, "🌆"),
    it("good_night", { en: "Good Night", ru: "Спокойной ночи", uk: "Добраніч", de: "Gute Nacht", fr: "Bonne nuit", pl: "Dobranoc" }, 19, "🌙"),
    it("happy_weekend", { en: "Happy Weekend", ru: "Хороших выходных", uk: "Гарних вихідних", de: "Schönes Wochenende", fr: "Bon week-end", pl: "Udanego weekendu" }, 20, "🎈"),
    it("good_luck", { en: "Good Luck", ru: "Удачи", uk: "Успіхів", de: "Viel Glück", fr: "Bonne chance", pl: "Powodzenia" }, 21, "🍀"),
    it("safe_travels", { en: "Safe Travels", ru: "Счастливого пути", uk: "Щасливої дороги", de: "Gute Reise", fr: "Bon voyage", pl: "Szczęśliwej podróży" }, 22, "✈️"),
    it("get_well", { en: "Get Well Soon", ru: "Скорейшего выздоровления", uk: "Швидкого одужання", de: "Gute Besserung", fr: "Bon rétablissement", pl: "Szybkiego powrotu do zdrowia" }, 23, "💊"),
    it("thank_you", { en: "Thank You", ru: "Спасибо", uk: "Дякую", de: "Danke", fr: "Merci", pl: "Dziękuję" }, 24, "🙏"),
    it("i_love_you", { en: "I Love You", ru: "Я тебя люблю", uk: "Я тебе кохаю", de: "Ich liebe dich", fr: "Je t'aime", pl: "Kocham cię" }, 25, "❤️"),
    it("i_miss_you", { en: "I Miss You", ru: "Я скучаю", uk: "Я сумую", de: "Ich vermisse dich", fr: "Tu me manques", pl: "Tęsknię za tobą" }, 26, "💌"),
    it("forgive_me", { en: "Forgive Me", ru: "Прости меня", uk: "Пробач мені", de: "Verzeih mir", fr: "Pardonne-moi", pl: "Wybacz mi" }, 27, "🥺"),
    it("reconciliation", { en: "Reconciliation", ru: "Примирение", uk: "Примирення", de: "Versöhnung", fr: "Réconciliation", pl: "Pojednanie" }, 28, "🤝"),
    it("thinking_of_you", { en: "Thinking of You", ru: "Думаю о тебе", uk: "Думаю про тебе", de: "Ich denke an dich", fr: "Je pense à toi", pl: "Myślę o tobie" }, 29, "💭"),
    it("encouragement", { en: "Encouragement", ru: "Поддержка", uk: "Підтримка", de: "Ermutigung", fr: "Encouragement", pl: "Wsparcie" }, 30, "🌟"),
    it("condolences", { en: "Condolences", ru: "Соболезнования", uk: "Співчуття", de: "Beileid", fr: "Condoléances", pl: "Kondolencje" }, 31, "🕯️"),
    it("christian_blessing", { en: "Christian Blessing", ru: "Христианское благословение", uk: "Християнське благословення", de: "Christlicher Segen", fr: "Bénédiction chrétienne", pl: "Chrześcijańskie błogosławieństwo" }, 32, "✝️"),
    it("bible_verse", { en: "Bible Verse", ru: "Библейский стих", uk: "Біблійний вірш", de: "Bibelvers", fr: "Verset biblique", pl: "Werset biblijny" }, 33, "📖"),
    it("prayer_support", { en: "Prayer Support", ru: "Молитвенная поддержка", uk: "Молитовна підтримка", de: "Gebetsunterstützung", fr: "Soutien par la prière", pl: "Modlitwa wsparcia" }, 34, "🙌"),
  ],
  recipient: [
    it("universal", { en: "Universal", ru: "Универсально", uk: "Універсально", de: "Universell", fr: "Universel", pl: "Uniwersalny" }, 1, "🌐"),
    it("mom", { en: "Mom", ru: "Мама", uk: "Мама", de: "Mama", fr: "Maman", pl: "Mama" }, 2, "👩"),
    it("dad", { en: "Dad", ru: "Папа", uk: "Тато", de: "Papa", fr: "Papa", pl: "Tata" }, 3, "👨"),
    it("daughter", { en: "Daughter", ru: "Дочь", uk: "Донька", de: "Tochter", fr: "Fille", pl: "Córka" }, 4, "👧"),
    it("son", { en: "Son", ru: "Сын", uk: "Син", de: "Sohn", fr: "Fils", pl: "Syn" }, 5, "👦"),
    it("grandma", { en: "Grandma", ru: "Бабушка", uk: "Бабуся", de: "Oma", fr: "Grand-mère", pl: "Babcia" }, 6, "👵"),
    it("grandpa", { en: "Grandpa", ru: "Дедушка", uk: "Дідусь", de: "Opa", fr: "Grand-père", pl: "Dziadek" }, 7, "👴"),
    it("wife", { en: "Wife", ru: "Жена", uk: "Дружина", de: "Ehefrau", fr: "Épouse", pl: "Żona" }, 8, "💗"),
    it("husband", { en: "Husband", ru: "Муж", uk: "Чоловік", de: "Ehemann", fr: "Époux", pl: "Mąż" }, 9, "💙"),
    it("beloved_woman", { en: "Beloved Woman", ru: "Любимая", uk: "Кохана", de: "Geliebte", fr: "Bien-aimée", pl: "Ukochana" }, 10, "💖"),
    it("beloved_man", { en: "Beloved Man", ru: "Любимый", uk: "Коханий", de: "Geliebter", fr: "Bien-aimé", pl: "Ukochany" }, 11, "💙"),
    it("sister", { en: "Sister", ru: "Сестра", uk: "Сестра", de: "Schwester", fr: "Sœur", pl: "Siostra" }, 12, "👭"),
    it("brother", { en: "Brother", ru: "Брат", uk: "Брат", de: "Bruder", fr: "Frère", pl: "Brat" }, 13, "👬"),
    it("friend", { en: "Friend", ru: "Друг", uk: "Друг", de: "Freund", fr: "Ami", pl: "Przyjaciel" }, 14, "🤝"),
    it("female_friend", { en: "Female Friend", ru: "Подруга", uk: "Подруга", de: "Freundin", fr: "Amie", pl: "Przyjaciółka" }, 15, "👯"),
    it("colleague", { en: "Colleague", ru: "Коллега", uk: "Колега", de: "Kollege", fr: "Collègue", pl: "Współpracownik" }, 16, "💼"),
    it("boss", { en: "Boss", ru: "Руководитель", uk: "Керівник", de: "Chef", fr: "Chef", pl: "Szef" }, 17, "🏢"),
    it("teacher", { en: "Teacher", ru: "Учитель", uk: "Вчитель", de: "Lehrer", fr: "Enseignant", pl: "Nauczyciel" }, 18, "📚"),
    it("educator", { en: "Educator", ru: "Воспитатель", uk: "Вихователь", de: "Erzieher", fr: "Éducateur", pl: "Wychowawca" }, 19, "🎨"),
    it("godmother", { en: "Godmother", ru: "Крёстная", uk: "Хрещена", de: "Patin", fr: "Marraine", pl: "Matka chrzestna" }, 20, "🕊️"),
    it("godfather", { en: "Godfather", ru: "Крёстный", uk: "Хрещений", de: "Pate", fr: "Parrain", pl: "Ojciec chrzestny" }, 21, "🕊️"),
    it("mother_in_law", { en: "Mother-in-law", ru: "Свекровь/Тёща", uk: "Свекруха/Теща", de: "Schwiegermutter", fr: "Belle-mère", pl: "Teściowa" }, 22, "👩‍🦳"),
    it("father_in_law", { en: "Father-in-law", ru: "Свёкор/Тесть", uk: "Свекор/Тесть", de: "Schwiegervater", fr: "Beau-père", pl: "Teść" }, 23, "👨‍🦳"),
    it("granddaughter", { en: "Granddaughter", ru: "Внучка", uk: "Онучка", de: "Enkelin", fr: "Petite-fille", pl: "Wnuczka" }, 24, "🎀"),
    it("grandson", { en: "Grandson", ru: "Внук", uk: "Онук", de: "Enkel", fr: "Petit-fils", pl: "Wnuk" }, 25, "⚽"),
    it("whole_family", { en: "Whole Family", ru: "Вся семья", uk: "Уся сім'я", de: "Ganze Familie", fr: "Toute la famille", pl: "Cała rodzina" }, 26, "👨‍👩‍👧‍👦"),
  ],
  style: [
    it("gentle", { en: "Gentle", ru: "Нежный", uk: "Ніжний", de: "Sanft", fr: "Doux", pl: "Delikatny" }, 1),
    it("romantic", { en: "Romantic", ru: "Романтичный", uk: "Романтичний", de: "Romantisch", fr: "Romantique", pl: "Romantyczny" }, 2),
    it("funny", { en: "Funny", ru: "Забавный", uk: "Веселий", de: "Lustig", fr: "Drôle", pl: "Zabawny" }, 3),
    it("elegant", { en: "Elegant", ru: "Элегантный", uk: "Елегантний", de: "Elegant", fr: "Élégant", pl: "Elegancki" }, 4),
    it("christian", { en: "Christian", ru: "Христианский", uk: "Християнський", de: "Christlich", fr: "Chrétien", pl: "Chrześcijański" }, 5),
    it("modern", { en: "Modern", ru: "Современный", uk: "Сучасний", de: "Modern", fr: "Moderne", pl: "Nowoczesny" }, 6),
    it("classic", { en: "Classic", ru: "Классический", uk: "Класичний", de: "Klassisch", fr: "Classique", pl: "Klasyczny" }, 7),
    it("luxurious", { en: "Luxurious", ru: "Роскошный", uk: "Розкішний", de: "Luxuriös", fr: "Luxueux", pl: "Luksusowy" }, 8),
    it("minimalist", { en: "Minimalist", ru: "Минималистичный", uk: "Мінімалістичний", de: "Minimalistisch", fr: "Minimaliste", pl: "Minimalistyczny" }, 9),
    it("floral", { en: "Floral", ru: "Цветочный", uk: "Квітковий", de: "Blumig", fr: "Fleuri", pl: "Kwiatowy" }, 10),
    it("animal", { en: "Animal", ru: "С животными", uk: "З тваринами", de: "Tiere", fr: "Animalier", pl: "Zwierzęcy" }, 11),
    it("nature", { en: "Nature", ru: "Природа", uk: "Природа", de: "Natur", fr: "Nature", pl: "Natura" }, 12),
    it("masculine", { en: "Masculine", ru: "Мужской", uk: "Чоловічий", de: "Männlich", fr: "Masculin", pl: "Męski" }, 13),
    it("feminine", { en: "Feminine", ru: "Женский", uk: "Жіночий", de: "Feminin", fr: "Féminin", pl: "Kobiecy" }, 14),
    it("children", { en: "Children", ru: "Детский", uk: "Дитячий", de: "Kinder", fr: "Enfants", pl: "Dziecięcy" }, 15),
    it("family", { en: "Family", ru: "Семейный", uk: "Сімейний", de: "Familie", fr: "Famille", pl: "Rodzinny" }, 16),
  ],
  mood: [
    it("warm", { en: "Warm", ru: "Тёплое", uk: "Тепле", de: "Warm", fr: "Chaleureux", pl: "Ciepły" }, 1),
    it("joyful", { en: "Joyful", ru: "Радостное", uk: "Радісне", de: "Fröhlich", fr: "Joyeux", pl: "Radosny" }, 2),
    it("peaceful", { en: "Peaceful", ru: "Спокойное", uk: "Спокійне", de: "Friedlich", fr: "Paisible", pl: "Spokojny" }, 3),
    it("solemn", { en: "Solemn", ru: "Торжественное", uk: "Урочисте", de: "Feierlich", fr: "Solennel", pl: "Uroczysty" }, 4),
    it("playful", { en: "Playful", ru: "Игривое", uk: "Грайливе", de: "Verspielt", fr: "Ludique", pl: "Zabawny" }, 5),
    it("emotional", { en: "Emotional", ru: "Эмоциональное", uk: "Емоційне", de: "Emotional", fr: "Émotionnel", pl: "Emocjonalny" }, 6),
    it("comforting", { en: "Comforting", ru: "Утешительное", uk: "Заспокійливе", de: "Tröstend", fr: "Réconfortant", pl: "Kojący" }, 7),
    it("inspirational", { en: "Inspirational", ru: "Вдохновляющее", uk: "Надихаюче", de: "Inspirierend", fr: "Inspirant", pl: "Inspirujący" }, 8),
  ],
  visualObject: [
    it("flowers", { en: "Flowers", ru: "Цветы", uk: "Квіти", de: "Blumen", fr: "Fleurs", pl: "Kwiaty" }, 1, "🌸"),
    it("roses", { en: "Roses", ru: "Розы", uk: "Троянди", de: "Rosen", fr: "Roses", pl: "Róże" }, 2, "🌹"),
    it("cake", { en: "Cake", ru: "Торт", uk: "Торт", de: "Kuchen", fr: "Gâteau", pl: "Tort" }, 3, "🍰"),
    it("hearts", { en: "Hearts", ru: "Сердца", uk: "Серця", de: "Herzen", fr: "Cœurs", pl: "Serca" }, 4, "💗"),
    it("candles", { en: "Candles", ru: "Свечи", uk: "Свічки", de: "Kerzen", fr: "Bougies", pl: "Świece" }, 5, "🕯️"),
    it("balloons", { en: "Balloons", ru: "Шары", uk: "Кульки", de: "Ballons", fr: "Ballons", pl: "Balony" }, 6, "🎈"),
    it("stars", { en: "Stars", ru: "Звёзды", uk: "Зірки", de: "Sterne", fr: "Étoiles", pl: "Gwiazdy" }, 7, "⭐"),
    it("landscape", { en: "Landscape", ru: "Пейзаж", uk: "Пейзаж", de: "Landschaft", fr: "Paysage", pl: "Krajobraz" }, 8, "🏞️"),
    it("sky", { en: "Sky", ru: "Небо", uk: "Небо", de: "Himmel", fr: "Ciel", pl: "Niebo" }, 9, "🌤️"),
    it("church", { en: "Church", ru: "Церковь", uk: "Церква", de: "Kirche", fr: "Église", pl: "Kościół" }, 10, "⛪"),
    it("cross", { en: "Cross", ru: "Крест", uk: "Хрест", de: "Kreuz", fr: "Croix", pl: "Krzyż" }, 11, "✝️"),
    it("gift_box", { en: "Gift Box", ru: "Подарок", uk: "Подарунок", de: "Geschenk", fr: "Cadeau", pl: "Prezent" }, 12, "🎁"),
  ],
  ageGroup: [],
  orientation: [],
  season: [
    it("spring", { en: "Spring", ru: "Весна", uk: "Весна", de: "Frühling", fr: "Printemps", pl: "Wiosna" }, 1, "🌸"),
    it("summer", { en: "Summer", ru: "Лето", uk: "Літо", de: "Sommer", fr: "Été", pl: "Lato" }, 2, "☀️"),
    it("autumn", { en: "Autumn", ru: "Осень", uk: "Осінь", de: "Herbst", fr: "Automne", pl: "Jesień" }, 3, "🍂"),
    it("winter", { en: "Winter", ru: "Зима", uk: "Зима", de: "Winter", fr: "Hiver", pl: "Zima" }, 4, "❄️"),
    it("all_seasons", { en: "All seasons", ru: "Все сезоны", uk: "Усі сезони", de: "Alle Jahreszeiten", fr: "Toutes saisons", pl: "Wszystkie pory roku" }, 5, "🌍"),
  ],
  theme: [
    it("nature", { en: "Nature", ru: "Природа", uk: "Природа", de: "Natur", fr: "Nature", pl: "Natura" }, 1, "🌿"),
    it("flowers", { en: "Flowers", ru: "Цветы", uk: "Квіти", de: "Blumen", fr: "Fleurs", pl: "Kwiaty" }, 2, "🌸"),
    it("animals", { en: "Animals", ru: "Животные", uk: "Тварини", de: "Tiere", fr: "Animaux", pl: "Zwierzęta" }, 3, "🐾"),
    it("jesus_christ", { en: "Jesus Christ", ru: "Иисус Христос", uk: "Ісус Христос", de: "Jesus Christus", fr: "Jésus-Christ", pl: "Jezus Chrystus" }, 4, "✝️"),
    it("angels", { en: "Angels", ru: "Ангелы", uk: "Янголи", de: "Engel", fr: "Anges", pl: "Anioły" }, 5, "👼"),
    it("family", { en: "Family", ru: "Семья", uk: "Родина", de: "Familie", fr: "Famille", pl: "Rodzina" }, 6, "👨‍👩‍👧"),
    it("love", { en: "Love", ru: "Любовь", uk: "Кохання", de: "Liebe", fr: "Amour", pl: "Miłość" }, 7, "❤️"),
    it("landscape", { en: "Landscape", ru: "Пейзаж", uk: "Пейзаж", de: "Landschaft", fr: "Paysage", pl: "Krajobraz" }, 8, "🏞️"),
    it("sea", { en: "Sea", ru: "Море", uk: "Море", de: "Meer", fr: "Mer", pl: "Morze" }, 9, "🌊"),
    it("sunrise", { en: "Sunrise", ru: "Рассвет", uk: "Світанок", de: "Sonnenaufgang", fr: "Lever de soleil", pl: "Wschód słońca" }, 10, "🌅"),
    it("sunset", { en: "Sunset", ru: "Закат", uk: "Захід сонця", de: "Sonnenuntergang", fr: "Coucher de soleil", pl: "Zachód słońca" }, 11, "🌇"),
    it("mountains", { en: "Mountains", ru: "Горы", uk: "Гори", de: "Berge", fr: "Montagnes", pl: "Góry" }, 12, "⛰️"),
    it("celebration", { en: "Celebration", ru: "Праздник", uk: "Свято", de: "Feier", fr: "Fête", pl: "Świętowanie" }, 13, "🎉"),
    it("children", { en: "Children", ru: "Дети", uk: "Діти", de: "Kinder", fr: "Enfants", pl: "Dzieci" }, 14, "🧒"),
    it("minimalism", { en: "Minimalism", ru: "Минимализм", uk: "Мінімалізм", de: "Minimalismus", fr: "Minimalisme", pl: "Minimalizm" }, 15, "◻️"),
    it("other", { en: "Other", ru: "Другое", uk: "Інше", de: "Sonstiges", fr: "Autre", pl: "Inne" }, 16, "✨"),
  ],
};

export function taxonomyLabel(items: TaxonomyItem[], key: string, lang: string): string {
  const it = items.find((i) => i.key === key);
  if (!it) return key;
  return (
    it.names[lang as keyof typeof it.names] ||
    it.names.en ||
    it.key
  );
}